apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
  name: vdsm-kube-ds
spec:
  template:
    metadata:
      labels:
        name: vdsm-kube-template
    spec:
      restartPolicy: "Always"
      hostIPC: true
      containers:
        - image: docker.io/bronhaim/vdsm-kube-logger:latest
          name: vdsm-kube-logger
          imagePullPolicy: "Always"
          ports:
            - containerPort: 514
              hostPort: 514

        - image: docker.io/bronhaim/vdsm-kube:latest
          name: vdsm-kube
          ports:
            - containerPort: 54321
              hostPort: 54321
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-fs-cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: dev
              mountPath: /dev
            - name: boot
              mountPath: /boot
          env:
            - name: OVIRT_FQDN
              valueFrom:
                configMapKeyRef:
                  name: vdsm-kube-config
                  key: engine.fqdn
            - name: CLUSTER_GATEWAY
              valueFrom:
                configMapKeyRef:
                  name: vdsm-kube-config
                  key: cluster.gateway
      volumes:
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dev
          hostPath:
            path: /dev
        - name: boot
          hostPath:
            path: /boot
