apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
  name: vdsm-kube-ds
spec:
  template:
    metadata:
      labels:
        name: vdsm-kube-template
    spec:
      restartPolicy: "Always"
      hostIPC: true
      containers:
        - image: docker.io/bronhaim/vdsm-kube-logger:latest
          name: vdsm-kube-logger
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 514
              protocol: TCP

        - image: docker.io/bronhaim/vdsm-kube:latest
          name: vdsm-kube
          ports:
            - containerPort: 54321
              protocol: TCP
          imagePullPolicy: "IfNotPresent"
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-fs-cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: dev
              mountPath: /dev
            - name: boot
              mountPath: /boot
          env:
            - name: OVIRT_FQDN
              value: ovirt-engine
            - name: CLUSTER_GATEWAY
              value: 172.17.0.1
      volumes:
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dev
          hostPath:
            path: /dev
        - name: boot
          hostPath:
            path: /boot
