apiVersion: v1
kind: Service
metadata:
  name: vdsm-kube-service
spec:
  selector:
    name: vdsm-kube-ds
  ports:
    - name: vdsm-kube-logger
      port: 514
      protocol: TCP
      targetPort: 514
    - name: vdsm-kube
      port: 54321
      protocol: TCP
      targetPort: 54321
  sessionAffinity: None
  type: ClusterIP
